# -*- coding: utf-8 -*-
"""Logfile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FKgvlSY48IHndUXe7oc5ki4yVrd3WpEk
"""

2024-12-15 12:34:56 [INFO] Connection established from 192.168.1.1
2024-12-15 12:34:57 [ERROR] Failed to connect from 192.168.1.2
Some random log line without IP
Another log with timestamp 12:35:00 and IPv4 10.0.0.1
2024-12-15 12:35:05 [INFO] Connection established from 192.168.1.3
2024-12-15 12:35:07 [ERROR] Failed to connect from 192.168.1.4